disabled_rules:
  - multiple_closures_with_trailing_closure
  - todo
opt_in_rules:
  - anyobject_protocol
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_optional_boolean
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - expiring_todo
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_name_no_space
  - flatmap_over_map_reduce
  - first_where
  - force_unwrapping
  - identical_operands
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - private_action
  - private_outlet
  - redundant_type_annotation
  - toggle_bool
  - unused_declaration
  - unused_import
  - yoda_condition
line_length: 165
type_body_length:
  warning: 300
  error: 300
file_length:
  warning: 550
  error: 550
function_body_length:
  warning: 100
  error: 100
function_parameter_count:
  warning: 6
  error: 6
type_name:
  min_length:
    warning: 2
    error: 2
  max_length:
    warning: 60
    error: 60
identifier_name:
  min_length:
    warning: 2
    error: 2
  max_length:
    warning: 60
    error: 80
enum_case_associated_values_count:
  warning: 4
  error: 4
cyclomatic_complexity:
  ignores_case_statements: true
