name: Trending

options:
  bundleIdPrefix: com.gwikiera
  groupOrdering: 
    - order: [Packages, Trending, TrendingUnitTests, TrendingSnapshotTests, TrendingUITests, TestPlans, Shared, Build Configs, Products]

configs:
  Debug: debug
  Debug-Unofficial: debug
  Debug-Mock: debug
  Release: release

configFiles:
  Debug: Trending/Build Configs/Debug.xcconfig
  Debug-Unofficial: Trending/Build Configs/Debug-Unofficial.xcconfig
  Debug-Mock: Trending/Build Configs/Debug-Mock.xcconfig
  Release: Trending/Build Configs/Release.xcconfig

packages:
  # local packages
  DesignSystem:
    path: DesignSystem
  Networking:
    path: Networking
  Model:
    path: Model
  GitHubAPIClient:
    path: GitHubAPIClient
  # remote packages
  ComposableArchitecture:
    url: "https://github.com/pointfreeco/swift-composable-architecture"
    from: "0.45.0"
  SnapshotTesting:
    url: "https://github.com/pointfreeco/swift-snapshot-testing"
    from: "1.10.0"
  CombineSchedulers:
    url: "https://github.com/pointfreeco/combine-schedulers"
    from: "0.9.1"

fileGroups: 
  - TestPlans

targets:
  Trending:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    dependencies:
      - package: DesignSystem
      - package: ComposableArchitecture
      - package: Networking
      - package: CombineSchedulers
      - package: Model
      - package: GitHubAPIClient
    sources: [Trending, Shared]
    postCompileScripts:
      - name: swiftlint
        script: |
                export PATH="$PATH:/opt/homebrew/bin"
                if which swiftlint > /dev/null; then
                  swiftlint
                else
                  echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
                fi
  TrendingUnitTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: TrendingUnitTests
        includes:
          - "**/*.swift"
    dependencies:
      - target: Trending
    settings:
      # makes xcode use the only target as host app
      - TEST_HOST: ""
  TrendingSnapshotTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: TrendingSnapshotTests
        includes:
          - "**/*SnapshotTests.swift"
        excludes:
          - "**/test*.png"
          - "**/__Snapshots__"
    dependencies:
      - target: Trending
      - package: SnapshotTesting
    settings:
      # makes xcode use the only target as host app
      - TEST_HOST: ""
  TrendingUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: TrendingUITests
        includes:
          - "**/*.swift"
      - path: Shared
        includes:
          - "**/*.swift"
    dependencies:
      - target: Trending

schemes:
  Trending:
    build:
      targets:
        Trending: [run, test, profile, analyze]
      preActions:
        - name: swiftgen
          script: |
                  if [[ -z "$CI" ]]; then
                    RUNNING_ON_CI=false
                  else
                    RUNNING_ON_CI=$CI
                  fi
                  if [[ "$RUNNING_ON_CI" = false ]]; then
                    export SWIFTGEN_PATH="${HOMEBREW_PREFIX}/bin/swiftgen"
                    if which "${SWIFTGEN_PATH}" >/dev/null; then
                      "${SWIFTGEN_PATH}" config run --config ${SRCROOT}/swiftgen.yml
                    else
                      echo "Warning: SwiftGen not installed"
                    fi
                  else
                    echo 'SwiftGen disabled for CI.'
                  fi
          settingsTarget: "Trending"
    run:
      config: Debug
    test:
      config: Debug
      testPlans:
        - path: TestPlans/UnitTests.xctestplan
        - path: TestPlans/AllTests.xctestplan
          defaultPlan: true
    profile:
      config: Release
    analyze:
      config: Release