default_platform(:ios)

test_device = "iPhone 14 Pro"

platform :ios do
  desc "Unit Tests"
  lane :unit_tests do
    test(test_plan: "UnitTests")
  end

  desc "All Tests"
  lane :all_tests do
    test(test_plan: "AllTests")
  end

# Private lanes
  private_lane :test do |options|
    scan(
      scheme: 'Trending-Mock',
      device: "iPhone 14 Pro",
      clean: true,
      testplan: options[:test_plan],
      code_coverage: true,
      result_bundle: true,
      output_directory: Dir.pwd + "/test_output/Trending"
    )
  end
end
