name: Integration # all tests
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  all_tests:
    runs-on: macos-12
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
      - run: brew install xcodegen
      - run: brew install swiftgen
      - run: sh bootstrap.sh
      - run: fastlane all_tests
      
      - name: "Tests results"
        uses: actions/upload-artifact@v3.0.0
        if: failure()
        with:
          name: fastlane-output 
          path: fastlane/test_output/
