name: Pull request # lint and unit tests
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
  
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: SwiftLint
      uses: norio-nomura/action-swiftlint@3.2.1
      with:
        args: --strict

  unit_tests:

    needs: lint
    runs-on: macos-12
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2
      - run: brew install xcodegen
      - run: brew install swiftgen
      - run: sh bootstrap.sh
      - run: fastlane unit_tests
